Models/Entities/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace dreamstarter_web.Models.Entities {
    public class Campaign{


        [Key]
        public int CampaignId { get; set; }
        public string Title {get; set;}
        public string ThemeImageFileName {get; set;}
        public double AmountRequired {get; set;}
        public double AmountRaised {get; set;}
        public string Synopsis {get; set;}
        public string DetailDescription {get; set;}
        public DateTime StartDate {get; set;}
        public DateTime EndDate { get; set; }
        public bool IsFinished {get; set; }
        

       //foreign key to User
       //ref. http://www.entityframeworktutorial.net/code-first/foreignkey-dataannotations-attribute-in-code-first.aspx
       public User User { get; set; }
       public int UserId { get; set; }

      

        //navigation properties
        public virtual IEnumerable<CommentCampaign> Comments {get; set;}
        public virtual IEnumerable<LikeCampaign> Likes {get; set;}
 
        

        
    }
}

Models/ViewModels/DetailCampaignViewModel.cs
using System;

namespace dreamstarter_web.Models.ViewModels{

    public class DetailCampaignViewModel{

        public int CampaignId { get; set; }
        public string Title {get; set;}
        public string ThemeImageFileName {get; set;}
        public double AmountRequired {get; set;}
        public double AmountRaised {get; set;}
        public string Synopsis {get; set;}
        public string DetailDescription {get; set;}
        public int PercentDone {get; set;}
        public DateTime EndDate { get; set; }
        public int DaysLeft {get; set;}
        public int NumberOfLikes{get; set;} // number of likes displayed on page reload
        public int UserId {get; set;} // to whom is detail campaign displayed

    }
}

Models/ViewModels/NewCampaignViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using dreamstarter_web.Models.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace dreamstarter_web.Models.ViewModels {

    public class NewCampaignViewModel{

        

        // //video
        // public string VideoTitle {get; set;}
        // public string VideoUrl {get; set;}

       
        [Required]
        public string Title {get; set;}

        //photo
        [Required]
        public IFormFile PhotoFile {get; set;}

        [Required]
        public string Synopsis{get; set;}
        [Required]
        public double AmountRequired {get; set;}

       [Required]
        public string DetailDescription{get; set;}

        //no model validation here
        public DateTime StartDate {get; set;}

        [Required]
        public DateTime EndDate {get; set;}

    
        
        

        
    }
}

Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using dreamstarter_web.Models.ViewModels;
using dreamstarter_web.Models.Entities;
using dreamstarter_web.Models.Repositories;
using dreamstarter_web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.Extensions.DependencyInjection;
using dreamstarter_web.Utilities;
using Microsoft.Extensions.FileProviders;
using System.Collections;

namespace dreamstarter_web.Controllers
{
    //[Authorize]
    public class CampaignController : Controller
    {
        private ICampaignRepository _campaignRepository;

        private readonly IFileProvider _fileProvider;
        private ILikeCampaignRepository _likeCampaignRepository;

        //Constructor
        public CampaignController(ICampaignRepository campaignRepository,
                                 IFileProvider fileProvider,
                                 ILikeCampaignRepository likeCampaignRepository)
        {
            _campaignRepository = campaignRepository;
            _fileProvider = fileProvider;
            _likeCampaignRepository = likeCampaignRepository;
        }

        [HttpGet]
        public IActionResult NewCampaign()
        {
            return View();
        }


        //crate new campaign
        [HttpPost]
        public async Task<IActionResult> NewCampaign(NewCampaignViewModel model)
        {
            // if (!ModelState.IsValid)
            // {
            //     return Content("something wrong with model");
            // }
            if(ModelState.IsValid){
                if (model.PhotoFile.Length == 0)
                return Content("file not selected");

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        model.PhotoFile.GetFilename());

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await model.PhotoFile.CopyToAsync(stream);
            }

        
            Campaign campaign = new Campaign();
            campaign.UserId = AccountController.UserId; // temporary solution
            campaign.Title = model.Title;
            campaign.ThemeImageFileName = model.PhotoFile.GetFilename();
            campaign.Synopsis = model.Synopsis;
            campaign.DetailDescription = model.DetailDescription;
            campaign.AmountRequired = model.AmountRequired;
            campaign.AmountRaised = 0;
            campaign.StartDate = DateTime.Now;
            campaign.EndDate = model.EndDate;

            _campaignRepository.Save(campaign);
            return RedirectToAction("Index", "Home");

            }
            return View();
            
        }

        [HttpGet]
        public IActionResult DetailCampaign(int Id)
        {

            Console.WriteLine("******************************* ID received: " + Id + "**************************************");
            //accessing particular - pointed - campaign from repository
            Campaign campaign = _campaignRepository.GetCampaignById(Id);

            int percentageDone = (int)Math.Floor((campaign.AmountRaised / campaign.AmountRequired) * 100);
            TimeSpan timeLeft = (campaign.EndDate - campaign.StartDate);
            //DateTime substracted gives TimeSpan object - one of it's properties are Days
            int daysLeft = timeLeft.Days;

            int likesNumber = _likeCampaignRepository.NumberOfLikes(Id);



            DetailCampaignViewModel dcvm = new DetailCampaignViewModel()
            {
                CampaignId = Id,
                Title = campaign.Title,
                Synopsis = campaign.Synopsis,
                ThemeImageFileName = campaign.ThemeImageFileName,
                AmountRequired = campaign.AmountRequired,
                DaysLeft = daysLeft,
                PercentDone = percentageDone,
                DetailDescription = campaign.DetailDescription,
                AmountRaised = campaign.AmountRaised,
                NumberOfLikes = likesNumber,
                UserId = AccountController.UserId
            };
            return View(dcvm);
        }


        //used to like campaign (DetailCampaign view)
        [Route("/api/like")]
        [HttpPost]
        public IActionResult LikeCampaign(LikeCampaignApiModel model)
        {
            //source: http://www.binaryintellect.net/articles/c69d78a3-21d7-416b-9d10-6b812a862778.aspx

            //'like' was pressed - like or unlike campaign - depending on state of the record
            Console.WriteLine(" Model from Json: " + model.CampaignId + "  " + AccountController.UserId);
            _likeCampaignRepository.LikeCampaign(AccountController.UserId, model.CampaignId);
            int numberOfLikes = _likeCampaignRepository.NumberOfLikes(model.CampaignId);
            return Json(numberOfLikes);
        }

        [Route("/api/fund")]
        [HttpPost]
        public IActionResult FundCampaign(FundModel fundmodel){
           
           double fund_update;

            if(!ModelState.IsValid){
                fund_update = -1;
                return Json(fund_update);
            }
            else{
               Console.WriteLine("Money comes: ************* " + fundmodel.CampaignId + " **** " + fundmodel.Amount);
               _campaignRepository.MakeDonation(fundmodel.CampaignId, fundmodel.Amount);
                fund_update = fundmodel.Amount;
                return Json(fund_update);
            }
        }

    }
}

Views/Campaign/DetailCampaign.cshtml
@model dreamstarter_web.Models.ViewModels.DetailCampaignViewModel

@{
    var camp = Model;
}
<head>
   
   
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $("#like").click(function(){
            if(@camp.UserId != 0){
                    $.post("/api/like", { CampaignId: @camp.CampaignId },
                function(data,status){
                        $("#likesNumber").text(data);
                });
            }
            else{
                alert("sory, please log in");
                //replace doesn't keep previous view in Session
                //useful for future
                //source:
                //https://stackoverflow.com/questions/503093/how-to-redirect-to-another-webpage
                window.location.replace("/account/login");
            }
           
        });

        $("#fund-button").on('click', function(){
            if(@camp.UserId != 0){
                <!-- location.reload(); -->
                $.post("/api/fund",
                { CampaignId: @camp.CampaignId, Amount: "100"},

                function(data,status){
                        var required = @camp.AmountRequired;
                        var raised = @camp.AmountRaised + data;
                        var procent_actual = Math.round(raised/required * 100);
                        $("#progress-bar").text(procent_actual + " %");
                        $("#amount-raised").text(raised + " DKK");
                        $("percent-of").text(raised + " of " + required + " DKK");
                });
                
            }
            else{
                alert("sory, please log in");
                //replace doesn't keep previous view in Session
                //useful for future
                //source:
                //https://stackoverflow.com/questions/503093/how-to-redirect-to-another-webpage
                window.location.replace("/account/login");
            }
           
        });

         $("#flip").click(function(){
        $("#panel").slideDown("slow");
    });
    });

    
</script>

 
<style> 
#panel {
    padding: 5px;
    text-align: center;
    background-color: #dddddd;
    opacity:0.5;
    border: solid 1px #c3c3c3;
}

#panel {
    padding: 50px;
    display: none;
}
</style>

</head>

<div class="container" id="container_main" style="margin-top:5em;">

    <!-- Title -->
    <div class="row" style="text-align:center; padding:3%;">
        <h1 >@camp.Title</h1>
    </div>

    <div class="row" style="margin-bottom:3%;">

        <!-- Left Column -->
        <div class="col-lg-8">
            
            <!-- Photo -->
            <dev>
                <img src="~/@camp.ThemeImageFileName" width="100%"/>
            </dev>

            <!-- Comment & Like -->
            <dev>
                 <a href="#" id="flip" class="btn btn-info btn-sm" style="margin-top:1%;" >
                    <span class="glyphicon glyphicon-comment"></span> Comment
                </a>
                <button id="like" class="btn btn-info btn-sm" style="margin-top:1%;">
                    <span class="glyphicon glyphicon-thumbs-up"></span> Like
                </button>
        
                    <span id="likesNumber" style="font-weight:bold; font-size:150%">@camp.NumberOfLikes</span>
                <div id="panel"> Comment </div>
            </dev>
            
            <!-- Synopsis -->
            <dev>
               <h3> @camp.Synopsis </h3> 
            </dev>
            <!-- Text - Details -->
            <dev>
                <h4>@camp.DetailDescription</h4>
            </dev>

            <!-- Comments -->
            <div style="margin-bottom:5%;">
                <h3>Comments:</h3>
            </div>

             
        </div>

        
        <!-- Right Column -->
        <div id="right-column" class="col-lg-4" style="padding-top: 1%; background-color:rgba(128, 128, 128, 0.164);">
           
            <!-- Button -->
            <div>
                <button id="fund-button" type="button" class="btn btn-primary btn-block Detail-Support-Btn">Support</button>
            </div>
            <!-- Campaign's Facts -->  
            <div class="progress">
                <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:@camp.PercentDone%; background-color:red;">@camp.PercentDone %</div>
            </div>
                <h1 id="amount-raised" style="padding-bottom:0px; margin-bottom:0px;">@camp.AmountRaised DKK</h1>
                <h4 id="percent-of" style="margin-top:0px; padding-top:0px;" >@camp.PercentDone% of @camp.AmountRequired DKK</h4>
                <h2 style="padding-bottom:0px; margin-bottom:0px;">@camp.DaysLeft</h2>  
                <h4 style="margin-top:0px; padding-top:0px;">days left</h4>
            </div>
        </div> 
    </div> 
    
</div><!-- End of Container -->

Views/Campaign/NewCampaign.cshtml
@model dreamstarter_web.Models.ViewModels.NewCampaignViewModel;

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Login</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" asp-href-include="~/css/*.css" />
        </environment>

        <style>
            .form-group{
                margin-top: 2em;    
            }
            
        </style>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
        $( function() {
            $( "#datepicker" ).datepicker();
        } );
        </script>

    </head>  
    
  <body>

        <div class="container">
            <form class="well" asp-controller="Campaign" asp-action="NewCampaign" method="post"
                enctype="multipart/form-data" class="input-group">
            <fieldset>

                <legend><center><h2><b>New Campaign</b></h2></center></legend><br>
                
                <dev asp-validation-summary="All" class="danger">           
                
                    <!-- Campaign's Title -->

                    <div class="row form-group">
                        <div class="col-md-4 input-GroupContainer">
                            <label class="control-label" asp-for="Title"></label>
                                <input  asp-for="Title" placeholder="Campaign's Title" class="form-control"  type="text">
                                <span asp-validation-for="Title" class ="text-danger"></span>
                         
                        </div>

                    <!-- Campaign's Theme Image -->

                         <div class="col-md-3 inputGroupContainer">
                                 <label class="control-label">Upload Campaign's Theme Image</label>
                                <input type="file" asp-for="PhotoFile"/>
                                <span asp-validation-for="PhotoFile" class ="text-danger"></span>
                        </div>

                <!-- Campaign's EndDate -->
                        <div class="col-md-4 input-GroupContainer absolute">
                            <label class="control-label" asp-for="EndDate">Please Choose Campaign's Final Date</label>
                            <input asp-for="EndDate" class="form-control absolute" type="text" id="datepicker" >
                            <span asp-validation-for="EndDate" class ="text-danger"></span>
                        </div>

                        <div class="col-md-4 input-GroupContainer" style="margin-top:2%;">
                            <label class="control-label" asp-for="AmountRequired"></label>
                                <input  asp-for="AmountRequired" placeholder="How much DKK would You like to collect" class="form-control"  type="text">
                                <span asp-validation-for="AmountRequired" class ="text-danger"></span>
                         
                        </div>
                
                       
                    </div>

                    

                    <!-- Synopsis -->

                    <div class="form-group">             
                        <label class="control-label" asp-for="Synopsis"></label> 
                        <div class="inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon">Text</span>
                                <textarea asp-for="Synopsis" Placeholder="Say in short what Your Campaign is all about" class="form-control" rows="4"></textarea>
                                <span asp-validation-for="Synopsis" class ="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <!-- Campaign's Details-->

                    <div class="form-group">
                        <label class="control-label" asp-for="DetailDescription">Detail Campaign Description</label> 
                        <div class="inputGroupContainer">
                            <div class="input-group">
                                <span class="input-group-addon">Text</span>
                                <textarea asp-for="DetailDescription"  placeholder="Detail Campaign's Description" class="form-control" rows="30"></textarea>
                                <span asp-validation-for="DetailDescription" class ="text-danger"></span>
                            </div>
                        </div>
                    </div>
        

                    <!-- Button -->
                    <div class="form-group">
                    <label class="control-label"></label>
                    <div>
                        <button type="submit" class="btn btn-warning" >SUBMIT <span class="glyphicon glyphicon-send"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button>
                    </div>
                    </div>
                </dev>
            </fieldset>
            </form>
            
            </div><!-- /.container -->
    </body>
</html>